apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: booklore-mcp-secret
  namespace: booklore-mcp
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: booklore-mcp-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        BOOKLORE_URL: "{{ .booklore_url }}"
        BOOKLORE_USERNAME: "{{ .booklore_username }}"
        BOOKLORE_PASSWORD: "{{ .booklore_password }}"
  data:
    - secretKey: booklore_url
      remoteRef:
        key: "booklore-mcp/booklore_url"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: booklore_username
      remoteRef:
        key: "booklore-mcp/booklore_username"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: booklore_password
      remoteRef:
        key: "booklore-mcp/booklore_password"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
